apiVersion: v1
kind: Service
metadata:
  name: nifi
spec:
  type: NodePort
  ports:
  - port: 9999
    nodePort: 30080
    targetPort: 9999
    protocol: TCP
  selector:
    app: nifi

---

apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - image: zanna94/nifi:latest
        name: nifi
        env:
          - name: NIFI_WEB_HTTP_PORT
            value: "9999"
 #         - name: NIFI_WEB_HTTP_HOST
 #           value: "nifi"
        ports:
        - containerPort: 9999
          name: webui
---
